### ISSUE TITLE
On-board debuggers not connecting to openOCD on Win-11

### ISSUE THREAD

**Issue by EdwinFairchild** [MaximIntegrated/max32625pico-firmware-images#1]
## Hardware 

- MAX32670 EV KIT
- MAX32655 FTHR

So this is an issue I am experiencing since updating to windows 11 from windows 10. Projects that once debugged and ran just find not get stuck with the following output on the Micros SDK console:

```
Open On-Chip Debugger 0.11.0+dev-g4f85f7914 (2021-12-16-13:53)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
DEPRECATED! use 'adapter driver' not 'interface'
DEPRECATED! use 'adapter srst delay' not 'adapter_nsrst_delay'
DEPRECATED! use 'adapter srst pulse_width' not 'adapter_nsrst_assert_width'
Started by GNU MCU Eclipse
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
```

Not sure if this is a windows 11 thing where some port settings or something is not what was previously assumed to be default. I reinstalled Micros SDK several times and the issue persisted. 
Then I installed Micros SDK on a Win 10 Machine and it worked as expected. 

Just wondering if I could get some insight on what causes the debugger to not get passed this `listening on port` state. 

## Steps to reproduce:

- Fresh Win 11
- Fresh Micros SDK install.
- Load up an example Project
- Build
- Try to Run/Debug

**Comment by ozersa** [comment]
It has been tested on W11, the issue not reproduced, 
It works as expected.
