### ISSUE TITLE
missing max32625_max32665hsp_if_crc.bin

### ISSUE THREAD

**Issue by fneirab** [MaximIntegrated/max32625pico-firmware-images#2]
This file is for the MRD104 daplink programmer and it is currently not visible in this page.
[MRD104_MAX_DAP_Firmware.zip](https://github.com/MaximIntegrated/max32625pico-firmware-images/files/8483720/MRD104_MAX_DAP_Firmware.zip)

**Comment by ozersa** [comment]
MRD104 is called as HSP3 platform.
MRD104 (HSP3) DAPLink fw is "MAX32666HSP3" it is listed on the table
![image](https://user-images.githubusercontent.com/46590392/199661138-09aa2f1e-950c-4761-89e8-3d75d04c2b7f.png)

**Comment by fneirab** [comment]
Great to know. Thanks!
